// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sbQJwsd5ZBs5BtGCQhhJLv
// Component: JyROVeReyh3D
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import NavBar from "../../NavBar"; // plasmic-import: YOpe0hL5L4N3/component
import Button from "../../Button"; // plasmic-import: 7ULaKDswMqpi/component
import ProductCard from "../../ProductCard"; // plasmic-import: 72J1CxYHdAMS/component
import Footer from "../../Footer"; // plasmic-import: I5piJM6JZjfm/component

import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ASb651IteQzF/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_ecommerce_starter.module.css"; // plasmic-import: sbQJwsd5ZBs5BtGCQhhJLv/projectcss
import * as sty from "./PlasmicCategory.module.css"; // plasmic-import: JyROVeReyh3D/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: pAQYl0DgHHRE/icon
import Icon33Icon from "./icons/PlasmicIcon__Icon33"; // plasmic-import: X352PtWdNIVx/icon
import Icon34Icon from "./icons/PlasmicIcon__Icon34"; // plasmic-import: RV0WuFuZOW-M/icon

export type PlasmicCategory__VariantMembers = {};

export type PlasmicCategory__VariantsArgs = {};
type VariantPropType = keyof PlasmicCategory__VariantsArgs;
export const PlasmicCategory__VariantProps = new Array<VariantPropType>();

export type PlasmicCategory__ArgsType = {};
type ArgPropType = keyof PlasmicCategory__ArgsType;
export const PlasmicCategory__ArgProps = new Array<ArgPropType>();

export type PlasmicCategory__OverridesType = {
  root?: p.Flex<"div">;
  navBar?: p.Flex<typeof NavBar>;
  section?: p.Flex<"section">;
  container6?: p.Flex<"div">;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultCategoryProps {
  dataFetches: PlasmicCategory__Fetches;
}

function PlasmicCategory__RenderFunc(props: {
  variants: PlasmicCategory__VariantsArgs;
  args: PlasmicCategory__ArgsType;
  overrides: PlasmicCategory__OverridesType;
  dataFetches?: PlasmicCategory__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <Head>
        <title key="title">{"Category"}</title>
        <meta key="og:title" property="og:title" content={"Category"} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={
            "Inceptos tempor torquent tortor a aptent parturient a a himenaeos in ipsum ad vestibulum euismod ultrices dis vulputate vestibulum non adipiscing."
          }
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar)}
            searchOpen={"searchOpen" as const}
          />

          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(defaultcss.all, sty.section)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"container6"}
              data-plasmic-override={overrides.container6}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container6)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__bSuHp)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__jTXtS)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___5SiR
                    )}
                  >
                    {"Categories"}
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__tpjPv)}
                    icons={"none" as const}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__mWrOr
                        )}
                      >
                        {"All"}
                      </div>
                    }
                    states={"active" as const}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__ikUop)}
                    icons={"none" as const}
                    slot={"New"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__jKfsN)}
                    icons={"none" as const}
                    slot={"Womens"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__gh3Oq)}
                    icons={"none" as const}
                    slot={"Mens"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__fkBNo)}
                    icons={"none" as const}
                    slot={"Kids"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__tXN4)}
                    icons={"none" as const}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__zZbHh
                        )}
                      >
                        {"On sale"}
                      </div>
                    }
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__f5XKp)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__nxBvL
                    )}
                  >
                    {"Price"}
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__e8SsK)}
                    icons={"none" as const}
                    slot={"$0 - $50"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__suoLp)}
                    icons={"none" as const}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__yBhSh
                        )}
                      >
                        {"$51 - $99"}
                      </div>
                    }
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__iFXud)}
                    icons={"none" as const}
                    slot={"$101+"}
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox___1J9Tw)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__gJvUy
                    )}
                  >
                    {"Colors"}
                  </div>

                  <div
                    className={classNames(defaultcss.all, sty.freeBox___2UV7Y)}
                  >
                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__goTx
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon33Icon
                        className={classNames(defaultcss.all, sty.svg__uoXcl)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__kfuDc
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon33Icon
                        className={classNames(defaultcss.all, sty.svg__f20Is)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__or0GF
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon33Icon
                        className={classNames(defaultcss.all, sty.svg__dEmhr)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__hkDQi
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon33Icon
                        className={classNames(defaultcss.all, sty.svg__d3Dp9)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__n0RN2
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon33Icon
                        className={classNames(defaultcss.all, sty.svg__mYdrv)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text___9QeUe
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon33Icon
                        className={classNames(defaultcss.all, sty.svg__afv8)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text___5GJxo
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon33Icon
                        className={classNames(defaultcss.all, sty.svg__phXqb)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__x0JjW
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon33Icon
                        className={classNames(defaultcss.all, sty.svg__dWett)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__zbn7D
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon33Icon
                        className={classNames(defaultcss.all, sty.svg__ctPLs)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__ryg2Z
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon33Icon
                        className={classNames(defaultcss.all, sty.svg__hzXf2)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__hPdWv
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon33Icon
                        className={classNames(defaultcss.all, sty.svg___49It)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text___9HvFe
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon33Icon
                        className={classNames(defaultcss.all, sty.svg__qxHyL)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__f4J83
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon33Icon
                        className={classNames(defaultcss.all, sty.svg__maxyN)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__uSm3W
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon33Icon
                        className={classNames(defaultcss.all, sty.svg__rNyP)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text___7WzKc
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon34Icon
                        className={classNames(defaultcss.all, sty.svg__ah0Um)}
                        role={"img"}
                      />
                    </Button>
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__ve07F)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___6DbDb
                    )}
                  >
                    {"Brands"}
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__a1VNz)}
                    icons={"none" as const}
                    slot={"Adidas"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__oq6Bn)}
                    icons={"none" as const}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__rynA
                        )}
                      >
                        {"Asics"}
                      </div>
                    }
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__x75Oc)}
                    icons={"none" as const}
                    slot={"Crocs"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__fenNn)}
                    icons={"none" as const}
                    slot={"Fila"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button___1KZsq)}
                    icons={"none" as const}
                    slot={"Nike"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__gBg1K)}
                    icons={"none" as const}
                    slot={"Puma"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button___68Smr)}
                    icons={"none" as const}
                    slot={"Reebok"}
                  />
                </p.Stack>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__nfPMk)}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__za6Ob
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__buwHs)}
                      src={
                        "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/0a659aab-5bb4-471e-adb3-beaf9be6e737/air-zoom-pegasus-38-limited-edition-womens-running-shoe-vmTQVG.png" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__rcLuk
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38 Limited Edition"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__ytXi0
                    )}
                  >
                    {"Women's Running Shoe"}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__wMfap
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__grZ8V)}
                      src={
                        "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/32735c84c423487da282ac790116ced8_9366/NMD_R1_Shoes_Blue_G55574_01_standard.jpg" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__ri4Q7
                    )}
                  >
                    {"NMD_R1 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___3Ae5B
                    )}
                  >
                    {"Continue the NMD legacy in these adidas NMD_R1 Shoes."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__mFah
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__avbYf)}
                      src={
                        "https://assets.reebok.com/images/w_320,f_auto,q_auto:sensitive,fl_lossy/dc6b2176848c4116b789acde0138ff10_9366/Question_Low_Men's_Basketball_Shoes_White_GV7629_01_standard.jpg" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__fnAcu
                    )}
                  >
                    {"Question Low Men's Basketball Shoes"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___9Ihwc
                    )}
                  >
                    {"Lace up fierce baller style."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__s1M0R
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img___5Nnpr)}
                      src={
                        "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/369155/04/sv03/fnd/PNA/fmt/png/Cali-Women's-Sneakers" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__xEn4C
                    )}
                  >
                    {"Cali Women's Sneakers"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__uiK5Y
                    )}
                  >
                    {"A sport style turned street classic."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__yDcfl
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__uO7I4)}
                      src={
                        "https://images.asics.com/is/image/asics/1011B026_600_SR_RT_GLB?$zoom$" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__mWibQ
                    )}
                  >
                    {"MAGIC SPEED"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___1SzGw
                    )}
                  >
                    {"mMade for racing or regular training runs."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___1PWqv
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__wxTme)}
                      src={
                        "https://www.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-cnv-master-catalog/default/dwfa98a04a/images/a_107/170823C_A_107X1.jpg?sw=964" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__vjkpH
                    )}
                  >
                    {"Pride Chuck Taylor All Star"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__z6Wsg
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__zvHsQ
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__w6Edp)}
                      src={
                        "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/c636bdcc-1f55-4cf5-9113-021b47c2fa86/air-zoom-pegasus-38-womens-running-shoe-wide-5JxKzR.png" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__xbTmp
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__qwZkn
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___82NtJ
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img___4PZmH)}
                      src={
                        "https://images.asics.com/is/image/asics/1011A780_100_SR_RT_GLB?$zoom$" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__eoCqk
                    )}
                  >
                    {"GEL-Nimbus 22 Retro Tokyo"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__zOgoZ
                    )}
                  >
                    {"Enjoy comfort with each stride."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__yXDgq
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__yeGh)}
                      src={
                        "https://www.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-cnv-master-catalog/default/dw388d0c95/images/a_107/670880C_A_107X1.jpg?sw=964" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__f7G70
                    )}
                  >
                    {"A Bug's World Chuck Taylor All Star"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__sDfC5
                    )}
                  >
                    {"Allover glow-in-the-dark bug prints."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___0Bzhp
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__tiuqt)}
                      src={
                        "https://assets.adidas.com/images/w_766,h_766,f_auto,q_auto:sensitive,fl_lossy/f63138f38e4f4469beaaacdb00fd9b89_9366/nmd_r1-shoes.jpg" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__m0UO
                    )}
                  >
                    {"NMD_R1 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__eViAq
                    )}
                  >
                    {
                      "Effortlessly step up your look than a pop of animal print."
                    }
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___3M9Y
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__k9LdV)}
                      src={
                        "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/380566/01/sv03/fnd/PNA/fmt/png/Suede-Teams-Little-Kids'-Shoes" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___0H0KV
                    )}
                  >
                    {"Suede Teams Little Kids' Shoes"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___67IBy
                    )}
                  >
                    {"Worn by the icons of every generation."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__jCf5E
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__sB1WH)}
                      src={
                        "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/226467aefe794e47a1ddac7201151dfa_9366/Superstar_360_Primeblue_Sandals_Yellow_FX4934_01_standard.jpg" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__kxxDh
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__wURaI
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__lpYid
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__oa40)}
                      src={
                        "https://pyxis.nymag.com/v1/imgs/537/58a/ddd6aab90b2387c93d86216de49dccfe4b-madewell-court-sneaker.2x.rsquare.w600.jpg" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__wnx88
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__z6FJ3
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__vmgtk
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__asw)}
                      src={
                        "https://cdn.shopify.com/s/files/1/2495/5044/products/oca-low-green-canvas-sneaker.slideshow1.jpg?v=1610694945" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__ufEg7
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__w4JoL
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__xsEhx
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__nTt6U)}
                      src={
                        "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/38277b478a79419abf6da998000ab640_9366/Runfalcon_Shoes_Black_F36218_01_standard.jpg" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__jjCtl
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__pQvKt
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___6NG3W
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__ztHpf)}
                      src={
                        "https://assets.adidas.com/images/w_600,f_auto,q_auto/4e894c2b76dd4c8e9013aafc016047af_9366/Superstar_Shoes_White_FV3284_01_standard.jpg" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__skwf
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___1BzLq
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>
              </p.Stack>
            </p.Stack>
          </section>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "navBar", "section", "container6", "footer"],
  navBar: ["navBar"],
  section: ["section", "container6"],
  container6: ["container6"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  navBar: typeof NavBar;
  section: "section";
  container6: "div";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCategory__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCategory__VariantsArgs;
    args?: PlasmicCategory__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicCategory__Fetches;
  } & Omit<PlasmicCategory__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicCategory__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCategory__ArgProps,
      internalVariantPropNames: PlasmicCategory__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicCategory__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCategory";
  } else {
    func.displayName = `PlasmicCategory.${nodeName}`;
  }
  return func;
}

export const PlasmicCategory = Object.assign(
  // Top-level PlasmicCategory renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    section: makeNodeComponent("section"),
    container6: makeNodeComponent("container6"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicCategory
    internalVariantProps: PlasmicCategory__VariantProps,
    internalArgProps: PlasmicCategory__ArgProps
  }
);

export default PlasmicCategory;
/* prettier-ignore-end */
