// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sbQJwsd5ZBs5BtGCQhhJLv
// Component: 3yXAqtnzialL
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import NavBar from "../../NavBar"; // plasmic-import: YOpe0hL5L4N3/component
import Button from "../../Button"; // plasmic-import: 7ULaKDswMqpi/component
import Separator from "../../Separator"; // plasmic-import: _XyEyKn2ynHq/component
import Footer from "../../Footer"; // plasmic-import: I5piJM6JZjfm/component

import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ASb651IteQzF/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_ecommerce_starter.module.css"; // plasmic-import: sbQJwsd5ZBs5BtGCQhhJLv/projectcss
import * as sty from "./PlasmicCart.module.css"; // plasmic-import: 3yXAqtnzialL/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: pAQYl0DgHHRE/icon
import Icon30Icon from "./icons/PlasmicIcon__Icon30"; // plasmic-import: ARkAwDI0QIUB/icon

export type PlasmicCart__VariantMembers = {
  filled: "filled";
};

export type PlasmicCart__VariantsArgs = {
  filled?: SingleBooleanChoiceArg<"filled">;
};

type VariantPropType = keyof PlasmicCart__VariantsArgs;
export const PlasmicCart__VariantProps = new Array<VariantPropType>("filled");

export type PlasmicCart__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
  slot3?: React.ReactNode;
  slot4?: React.ReactNode;
  slot5?: React.ReactNode;
};

type ArgPropType = keyof PlasmicCart__ArgsType;
export const PlasmicCart__ArgProps = new Array<ArgPropType>(
  "children",
  "slot",
  "slot2",
  "slot3",
  "slot4",
  "slot5"
);

export type PlasmicCart__OverridesType = {
  root?: p.Flex<"div">;
  navBar?: p.Flex<typeof NavBar>;
  section?: p.Flex<"section">;
  container2?: p.Flex<"div">;
  separator?: p.Flex<typeof Separator>;
  svg?: p.Flex<"svg">;
  container?: p.Flex<"div">;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultCartProps {
  dataFetches: PlasmicCart__Fetches;
}

function PlasmicCart__RenderFunc(props: {
  variants: PlasmicCart__VariantsArgs;
  args: PlasmicCart__ArgsType;
  overrides: PlasmicCart__OverridesType;
  dataFetches?: PlasmicCart__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <Head>
        <title key="title">{"Shopping Cart"}</title>
        <meta key="og:title" property="og:title" content={"Shopping Cart"} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={
            "Congue pulvinar scelerisque vestibulum senectus ullamcorper ac sem justo odio adipiscing volutpat nam a amet quam facilisi parturient parturient et id parturient per."
          }
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root,
            { [sty.root__filled]: hasVariant(variants, "filled", "filled") }
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar, {
              [sty.navBar__filled]: hasVariant(variants, "filled", "filled")
            })}
            filled={
              hasVariant(variants, "filled", "filled")
                ? ("filled" as const)
                : undefined
            }
          />

          <p.Stack
            as={"section"}
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            hasGap={true}
            className={classNames(defaultcss.all, sty.section)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"container2"}
              data-plasmic-override={overrides.container2}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container2, {
                [sty.container2__filled]: hasVariant(
                  variants,
                  "filled",
                  "filled"
                )
              })}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__e0KuL, {
                  [sty.freeBox__filled__e0KuLUzZv]: hasVariant(
                    variants,
                    "filled",
                    "filled"
                  )
                })}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__oMpy, {
                    [sty.freeBox__filled__oMpyUzZv]: hasVariant(
                      variants,
                      "filled",
                      "filled"
                    )
                  })}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___1Khf,
                      {
                        [sty.text__filled___1KhfUzZv]: hasVariant(
                          variants,
                          "filled",
                          "filled"
                        )
                      }
                    )}
                  >
                    {"Order Summary"}
                  </div>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__b39Fw, {
                      [sty.freeBox__filled__b39FwUzZv]: hasVariant(
                        variants,
                        "filled",
                        "filled"
                      )
                    })}
                  >
                    <div
                      className={classNames(defaultcss.all, sty.freeBox__cdt9F)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__cs87I,
                          {
                            [sty.freeBox__filled__cs87IUzZv]: hasVariant(
                              variants,
                              "filled",
                              "filled"
                            )
                          }
                        )}
                      >
                        {p.renderPlasmicSlot({
                          defaultContents: hasVariant(
                            variants,
                            "filled",
                            "filled"
                          )
                            ? "Subtotal (1)"
                            : "Subtotal (0)",
                          value: args.slot5,
                          className: classNames(sty.slotSlot5, {
                            [sty.slotSlot5__filled]: hasVariant(
                              variants,
                              "filled",
                              "filled"
                            )
                          })
                        })}
                      </div>

                      <div
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__gWngh,
                          {
                            [sty.freeBox__filled__gWnghUzZv]: hasVariant(
                              variants,
                              "filled",
                              "filled"
                            )
                          }
                        )}
                      >
                        {p.renderPlasmicSlot({
                          defaultContents: hasVariant(
                            variants,
                            "filled",
                            "filled"
                          )
                            ? "$88.99"
                            : "$0.00",
                          value: args.children,
                          className: classNames(sty.slotChildren, {
                            [sty.slotChildren__filled]: hasVariant(
                              variants,
                              "filled",
                              "filled"
                            )
                          })
                        })}
                      </div>
                    </div>

                    <div
                      className={classNames(defaultcss.all, sty.freeBox__mEpRp)}
                    >
                      {(
                        hasVariant(variants, "filled", "filled") ? true : true
                      ) ? (
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__ayMvU,
                            {
                              [sty.text__filled__ayMvUUzZv]: hasVariant(
                                variants,
                                "filled",
                                "filled"
                              )
                            }
                          )}
                        >
                          {"Estimated Shipping (free over $49)"}
                        </div>
                      ) : null}

                      <div
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__bgU56,
                          {
                            [sty.freeBox__filled__bgU56UzZv]: hasVariant(
                              variants,
                              "filled",
                              "filled"
                            )
                          }
                        )}
                      >
                        {p.renderPlasmicSlot({
                          defaultContents: hasVariant(
                            variants,
                            "filled",
                            "filled"
                          )
                            ? "FREE"
                            : "-",
                          value: args.slot,
                          className: classNames(sty.slotSlot, {
                            [sty.slotSlot__filled]: hasVariant(
                              variants,
                              "filled",
                              "filled"
                            )
                          })
                        })}
                      </div>
                    </div>

                    <div
                      className={classNames(defaultcss.all, sty.freeBox__sciby)}
                    >
                      {(
                        hasVariant(variants, "filled", "filled") ? true : true
                      ) ? (
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__kL57,
                            {
                              [sty.text__filled__kL57UzZv]: hasVariant(
                                variants,
                                "filled",
                                "filled"
                              )
                            }
                          )}
                        >
                          {"Estimated Tax"}
                        </div>
                      ) : null}

                      <div
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__l9Qtd,
                          {
                            [sty.freeBox__filled__l9QtdUzZv]: hasVariant(
                              variants,
                              "filled",
                              "filled"
                            )
                          }
                        )}
                      >
                        {p.renderPlasmicSlot({
                          defaultContents: "-",
                          value: args.slot2,
                          className: classNames(sty.slotSlot2, {
                            [sty.slotSlot2__filled]: hasVariant(
                              variants,
                              "filled",
                              "filled"
                            )
                          })
                        })}
                      </div>
                    </div>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button___5PtXz,
                        {
                          [sty.button__filled___5PtXzUzZv]: hasVariant(
                            variants,
                            "filled",
                            "filled"
                          )
                        }
                      )}
                      icons={"none" as const}
                      link={"link" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__wA8Z4
                          )}
                        >
                          {"Have a promo code?"}
                        </div>
                      }
                    />

                    <Separator
                      data-plasmic-name={"separator"}
                      data-plasmic-override={overrides.separator}
                      className={classNames("__wab_instance", sty.separator)}
                      dark={"dark" as const}
                    />

                    <div
                      className={classNames(defaultcss.all, sty.freeBox__p6Wg, {
                        [sty.freeBox__filled__p6WgUzZv]: hasVariant(
                          variants,
                          "filled",
                          "filled"
                        )
                      })}
                    >
                      {(
                        hasVariant(variants, "filled", "filled") ? true : true
                      ) ? (
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__laTex,
                            {
                              [sty.text__filled__laTexUzZv]: hasVariant(
                                variants,
                                "filled",
                                "filled"
                              )
                            }
                          )}
                        >
                          {"Estimated Total"}
                        </div>
                      ) : null}

                      <div
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__bRpkC,
                          {
                            [sty.freeBox__filled__bRpkCUzZv]: hasVariant(
                              variants,
                              "filled",
                              "filled"
                            )
                          }
                        )}
                      >
                        {p.renderPlasmicSlot({
                          defaultContents: hasVariant(
                            variants,
                            "filled",
                            "filled"
                          )
                            ? "$88.99"
                            : "$0.00",
                          value: args.slot4,
                          className: classNames(sty.slotSlot4, {
                            [sty.slotSlot4__filled]: hasVariant(
                              variants,
                              "filled",
                              "filled"
                            )
                          })
                        })}
                      </div>
                    </div>

                    {(hasVariant(variants, "filled", "filled") ? true : false)
                      ? p.renderPlasmicSlot({
                          defaultContents: true ? (
                            <Button
                              className={classNames(
                                "__wab_instance",
                                sty.button__aqAeq
                              )}
                              colors={"blue" as const}
                              icons={"none" as const}
                              rounded={"rounded" as const}
                              size={"large" as const}
                              slot={
                                <div
                                  className={classNames(
                                    defaultcss.all,
                                    defaultcss.__wab_text,
                                    sty.text___3GIpv
                                  )}
                                >
                                  {"Checkout"}
                                </div>
                              }
                            />
                          ) : null,
                          value: args.slot3
                        })
                      : null}

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        defaultcss.all,
                        sty.freeBox___5Oc1L,
                        {
                          [sty.freeBox__filled___5Oc1LUzZv]: hasVariant(
                            variants,
                            "filled",
                            "filled"
                          )
                        }
                      )}
                    >
                      <Icon30Icon
                        data-plasmic-name={"svg"}
                        data-plasmic-override={overrides.svg}
                        className={classNames(defaultcss.all, sty.svg)}
                        role={"img"}
                      />

                      {(
                        hasVariant(variants, "filled", "filled") ? true : true
                      ) ? (
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__qnPjk,
                            {
                              [sty.text__filled__qnPjkUzZv]: hasVariant(
                                variants,
                                "filled",
                                "filled"
                              )
                            }
                          )}
                        >
                          {"Secure"}
                        </div>
                      ) : null}
                    </p.Stack>
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__pMqSj, {
                    [sty.freeBox__filled__pMqSjUzZv]: hasVariant(
                      variants,
                      "filled",
                      "filled"
                    )
                  })}
                >
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__sfCis)}
                    src={"/plasmic/ecommerce_starter/images/image.svg"}
                  />

                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__vkz8X)}
                    src={"/plasmic/ecommerce_starter/images/image2.svg"}
                  />

                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img___6HWLw)}
                    src={"/plasmic/ecommerce_starter/images/image3.svg"}
                  />

                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__lQm5G)}
                    src={"/plasmic/ecommerce_starter/images/image4.svg"}
                  />
                </p.Stack>
              </p.Stack>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container, {
                [sty.container__filled]: hasVariant(
                  variants,
                  "filled",
                  "filled"
                )
              })}
            >
              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__mirzI)}
                src={
                  "https://www.patagonia.com/on/demandware.static/-/Library-Sites-PatagoniaShared/default/dw4b201dc8/images/for-the-planet.png" as const
                }
              />

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__bY5F3)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text__pMuQ
                  )}
                >
                  {"1% of your purchase will go to a grassroot organization."}
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__kiXg)}
                  icons={"none" as const}
                  link={"link" as const}
                  slot={"Learn more"}
                />
              </p.Stack>
            </p.Stack>
          </p.Stack>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navBar",
    "section",
    "container2",
    "separator",
    "svg",
    "container",
    "footer"
  ],
  navBar: ["navBar"],
  section: ["section", "container2", "separator", "svg", "container"],
  container2: ["container2", "separator", "svg"],
  separator: ["separator"],
  svg: ["svg"],
  container: ["container"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  navBar: typeof NavBar;
  section: "section";
  container2: "div";
  separator: typeof Separator;
  svg: "svg";
  container: "div";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCart__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCart__VariantsArgs;
    args?: PlasmicCart__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicCart__Fetches;
  } & Omit<PlasmicCart__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicCart__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCart__ArgProps,
      internalVariantPropNames: PlasmicCart__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicCart__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCart";
  } else {
    func.displayName = `PlasmicCart.${nodeName}`;
  }
  return func;
}

export const PlasmicCart = Object.assign(
  // Top-level PlasmicCart renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    section: makeNodeComponent("section"),
    container2: makeNodeComponent("container2"),
    separator: makeNodeComponent("separator"),
    svg: makeNodeComponent("svg"),
    container: makeNodeComponent("container"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicCart
    internalVariantProps: PlasmicCart__VariantProps,
    internalArgProps: PlasmicCart__ArgProps
  }
);

export default PlasmicCart;
/* prettier-ignore-end */
