// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sbQJwsd5ZBs5BtGCQhhJLv
// Component: 7ULaKDswMqpi
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_ecommerce_starter.module.css"; // plasmic-import: sbQJwsd5ZBs5BtGCQhhJLv/projectcss
import * as sty from "./PlasmicButton.module.css"; // plasmic-import: 7ULaKDswMqpi/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: pAQYl0DgHHRE/icon

export type PlasmicButton__VariantMembers = {
  icons: "none" | "end" | "both" | "only" | "five";
  colors:
    | "gray"
    | "white"
    | "blue"
    | "black"
    | "lightGray"
    | "lightGrayOutline";
  size: "large" | "small" | "narrow";
  rounded: "rounded";
  link: "link";
  states: "active";
};

export type PlasmicButton__VariantsArgs = {
  icons?: SingleChoiceArg<"none" | "end" | "both" | "only" | "five">;
  colors?: SingleChoiceArg<
    "gray" | "white" | "blue" | "black" | "lightGray" | "lightGrayOutline"
  >;
  size?: SingleChoiceArg<"large" | "small" | "narrow">;
  rounded?: SingleBooleanChoiceArg<"rounded">;
  link?: SingleBooleanChoiceArg<"link">;
  states?: SingleChoiceArg<"active">;
};

type VariantPropType = keyof PlasmicButton__VariantsArgs;
export const PlasmicButton__VariantProps = new Array<VariantPropType>(
  "icons",
  "colors",
  "size",
  "rounded",
  "link",
  "states"
);

export type PlasmicButton__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  children2?: React.ReactNode;
  children3?: React.ReactNode;
  children32?: React.ReactNode;
  children322?: React.ReactNode;
  children3222?: React.ReactNode;
  link2?: string | PageHref;
};

type ArgPropType = keyof PlasmicButton__ArgsType;
export const PlasmicButton__ArgProps = new Array<ArgPropType>(
  "children",
  "slot",
  "children2",
  "children3",
  "children32",
  "children322",
  "children3222",
  "link2"
);

export type PlasmicButton__OverridesType = {
  root?: p.Flex<"a"> & Partial<LinkProps>;
};

export interface DefaultButtonProps {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  children2?: React.ReactNode;
  children3?: React.ReactNode;
  children32?: React.ReactNode;
  children322?: React.ReactNode;
  children3222?: React.ReactNode;
  link2?: string | PageHref;
  icons?: SingleChoiceArg<"none" | "end" | "both" | "only" | "five">;
  colors?: SingleChoiceArg<
    "gray" | "white" | "blue" | "black" | "lightGray" | "lightGrayOutline"
  >;
  size?: SingleChoiceArg<"large" | "small" | "narrow">;
  rounded?: SingleBooleanChoiceArg<"rounded">;
  link?: SingleBooleanChoiceArg<"link">;
  states?: SingleChoiceArg<"active">;
  className?: string;
}

function PlasmicButton__RenderFunc(props: {
  variants: PlasmicButton__VariantsArgs;
  args: PlasmicButton__ArgsType;
  overrides: PlasmicButton__OverridesType;
  dataFetches?: PlasmicButton__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.Stack
      as={p.PlasmicLink}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__colors_black]: hasVariant(variants, "colors", "black"),
        [sty.root__colors_blue]: hasVariant(variants, "colors", "blue"),
        [sty.root__colors_gray]: hasVariant(variants, "colors", "gray"),
        [sty.root__colors_lightGrayOutline]: hasVariant(
          variants,
          "colors",
          "lightGrayOutline"
        ),
        [sty.root__colors_lightGray]: hasVariant(
          variants,
          "colors",
          "lightGray"
        ),
        [sty.root__colors_white]: hasVariant(variants, "colors", "white"),
        [sty.root__icons_end]: hasVariant(variants, "icons", "end"),
        [sty.root__icons_five]: hasVariant(variants, "icons", "five"),
        [sty.root__icons_none]: hasVariant(variants, "icons", "none"),
        [sty.root__link]: hasVariant(variants, "link", "link"),
        [sty.root__rounded]: hasVariant(variants, "rounded", "rounded"),
        [sty.root__rounded_size_large]:
          hasVariant(variants, "rounded", "rounded") &&
          hasVariant(variants, "size", "large"),
        [sty.root__size_large]: hasVariant(variants, "size", "large"),
        [sty.root__size_narrow]: hasVariant(variants, "size", "narrow"),
        [sty.root__size_small]: hasVariant(variants, "size", "small"),
        [sty.root__states_active]: hasVariant(variants, "states", "active")
      })}
      component={Link}
      href={args.link2}
      platform={"nextjs"}
    >
      {(
        hasVariant(variants, "icons", "end")
          ? false
          : hasVariant(variants, "icons", "none")
          ? false
          : true
      ) ? (
        <div
          className={classNames(defaultcss.all, sty.freeBox__oGdhi, {
            [sty.freeBox__icons_end__oGdhion4Z]: hasVariant(
              variants,
              "icons",
              "end"
            ),
            [sty.freeBox__icons_five__oGdhizqPth]: hasVariant(
              variants,
              "icons",
              "five"
            ),
            [sty.freeBox__icons_none__oGdhiRfRl]: hasVariant(
              variants,
              "icons",
              "none"
            ),
            [sty.freeBox__size_large__oGdhiOz915]: hasVariant(
              variants,
              "size",
              "large"
            ),
            [sty.freeBox__size_small__oGdhiYgvP7]: hasVariant(
              variants,
              "size",
              "small"
            )
          })}
        >
          {(
            hasVariant(variants, "icons", "end")
              ? true
              : hasVariant(variants, "icons", "none")
              ? true
              : true
          )
            ? p.renderPlasmicSlot({
                defaultContents: (
                  <IconIcon
                    className={classNames(defaultcss.all, sty.svg__o0Z4I)}
                    role={"img"}
                  />
                ),

                value: args.children,
                className: classNames(sty.slotChildren, {
                  [sty.slotChildren__colors_black]: hasVariant(
                    variants,
                    "colors",
                    "black"
                  ),
                  [sty.slotChildren__colors_blue]: hasVariant(
                    variants,
                    "colors",
                    "blue"
                  ),
                  [sty.slotChildren__colors_gray]: hasVariant(
                    variants,
                    "colors",
                    "gray"
                  ),
                  [sty.slotChildren__icons_end]: hasVariant(
                    variants,
                    "icons",
                    "end"
                  ),
                  [sty.slotChildren__icons_five]: hasVariant(
                    variants,
                    "icons",
                    "five"
                  ),
                  [sty.slotChildren__icons_none]: hasVariant(
                    variants,
                    "icons",
                    "none"
                  ),
                  [sty.slotChildren__size_large]: hasVariant(
                    variants,
                    "size",
                    "large"
                  ),
                  [sty.slotChildren__size_small]: hasVariant(
                    variants,
                    "size",
                    "small"
                  )
                })
              })
            : null}
        </div>
      ) : null}
      {(
        hasVariant(variants, "icons", "five")
          ? true
          : hasVariant(variants, "icons", "end")
          ? false
          : hasVariant(variants, "icons", "none")
          ? false
          : false
      ) ? (
        <div
          className={classNames(defaultcss.all, sty.freeBox__g03O, {
            [sty.freeBox__icons_end__g03Oon4Z]: hasVariant(
              variants,
              "icons",
              "end"
            ),
            [sty.freeBox__icons_five__g03OzqPth]: hasVariant(
              variants,
              "icons",
              "five"
            ),
            [sty.freeBox__icons_none__g03OrfRl]: hasVariant(
              variants,
              "icons",
              "none"
            ),
            [sty.freeBox__size_large__g03OOz915]: hasVariant(
              variants,
              "size",
              "large"
            ),
            [sty.freeBox__size_small__g03OYgvP7]: hasVariant(
              variants,
              "size",
              "small"
            )
          })}
        >
          {(
            hasVariant(variants, "icons", "end")
              ? true
              : hasVariant(variants, "icons", "none")
              ? true
              : true
          )
            ? p.renderPlasmicSlot({
                defaultContents: (
                  <IconIcon
                    className={classNames(defaultcss.all, sty.svg__hNAz)}
                    role={"img"}
                  />
                ),

                value: args.children3,
                className: classNames(sty.slotChildren3, {
                  [sty.slotChildren3__colors_black]: hasVariant(
                    variants,
                    "colors",
                    "black"
                  ),
                  [sty.slotChildren3__colors_blue]: hasVariant(
                    variants,
                    "colors",
                    "blue"
                  ),
                  [sty.slotChildren3__colors_gray]: hasVariant(
                    variants,
                    "colors",
                    "gray"
                  ),
                  [sty.slotChildren3__icons_end]: hasVariant(
                    variants,
                    "icons",
                    "end"
                  ),
                  [sty.slotChildren3__icons_none]: hasVariant(
                    variants,
                    "icons",
                    "none"
                  ),
                  [sty.slotChildren3__size_large]: hasVariant(
                    variants,
                    "size",
                    "large"
                  ),
                  [sty.slotChildren3__size_small]: hasVariant(
                    variants,
                    "size",
                    "small"
                  )
                })
              })
            : null}
        </div>
      ) : null}
      {(
        hasVariant(variants, "icons", "five")
          ? true
          : hasVariant(variants, "icons", "end")
          ? false
          : hasVariant(variants, "icons", "none")
          ? false
          : false
      ) ? (
        <div
          className={classNames(defaultcss.all, sty.freeBox__hbraP, {
            [sty.freeBox__icons_end__hbraPon4Z]: hasVariant(
              variants,
              "icons",
              "end"
            ),
            [sty.freeBox__icons_five__hbraPzqPth]: hasVariant(
              variants,
              "icons",
              "five"
            ),
            [sty.freeBox__icons_none__hbraPrfRl]: hasVariant(
              variants,
              "icons",
              "none"
            ),
            [sty.freeBox__size_large__hbraPOz915]: hasVariant(
              variants,
              "size",
              "large"
            ),
            [sty.freeBox__size_small__hbraPYgvP7]: hasVariant(
              variants,
              "size",
              "small"
            )
          })}
        >
          {(
            hasVariant(variants, "icons", "end")
              ? true
              : hasVariant(variants, "icons", "none")
              ? true
              : true
          )
            ? p.renderPlasmicSlot({
                defaultContents: (
                  <IconIcon
                    className={classNames(defaultcss.all, sty.svg__i12C)}
                    role={"img"}
                  />
                ),

                value: args.children32,
                className: classNames(sty.slotChildren32, {
                  [sty.slotChildren32__colors_black]: hasVariant(
                    variants,
                    "colors",
                    "black"
                  ),
                  [sty.slotChildren32__colors_blue]: hasVariant(
                    variants,
                    "colors",
                    "blue"
                  ),
                  [sty.slotChildren32__colors_gray]: hasVariant(
                    variants,
                    "colors",
                    "gray"
                  ),
                  [sty.slotChildren32__icons_end]: hasVariant(
                    variants,
                    "icons",
                    "end"
                  ),
                  [sty.slotChildren32__icons_none]: hasVariant(
                    variants,
                    "icons",
                    "none"
                  ),
                  [sty.slotChildren32__size_large]: hasVariant(
                    variants,
                    "size",
                    "large"
                  ),
                  [sty.slotChildren32__size_small]: hasVariant(
                    variants,
                    "size",
                    "small"
                  )
                })
              })
            : null}
        </div>
      ) : null}
      {(
        hasVariant(variants, "icons", "five")
          ? true
          : hasVariant(variants, "icons", "end")
          ? false
          : hasVariant(variants, "icons", "none")
          ? false
          : false
      ) ? (
        <div
          className={classNames(defaultcss.all, sty.freeBox__iNxEi, {
            [sty.freeBox__icons_end__iNxEIon4Z]: hasVariant(
              variants,
              "icons",
              "end"
            ),
            [sty.freeBox__icons_five__iNxEIzqPth]: hasVariant(
              variants,
              "icons",
              "five"
            ),
            [sty.freeBox__icons_none__iNxEirfRl]: hasVariant(
              variants,
              "icons",
              "none"
            ),
            [sty.freeBox__size_large__iNxEiOz915]: hasVariant(
              variants,
              "size",
              "large"
            ),
            [sty.freeBox__size_small__iNxEiYgvP7]: hasVariant(
              variants,
              "size",
              "small"
            )
          })}
        >
          {(
            hasVariant(variants, "icons", "end")
              ? true
              : hasVariant(variants, "icons", "none")
              ? true
              : true
          )
            ? p.renderPlasmicSlot({
                defaultContents: (
                  <IconIcon
                    className={classNames(defaultcss.all, sty.svg__gHhE)}
                    role={"img"}
                  />
                ),

                value: args.children322,
                className: classNames(sty.slotChildren322, {
                  [sty.slotChildren322__colors_black]: hasVariant(
                    variants,
                    "colors",
                    "black"
                  ),
                  [sty.slotChildren322__colors_blue]: hasVariant(
                    variants,
                    "colors",
                    "blue"
                  ),
                  [sty.slotChildren322__colors_gray]: hasVariant(
                    variants,
                    "colors",
                    "gray"
                  ),
                  [sty.slotChildren322__icons_end]: hasVariant(
                    variants,
                    "icons",
                    "end"
                  ),
                  [sty.slotChildren322__icons_none]: hasVariant(
                    variants,
                    "icons",
                    "none"
                  ),
                  [sty.slotChildren322__size_large]: hasVariant(
                    variants,
                    "size",
                    "large"
                  ),
                  [sty.slotChildren322__size_small]: hasVariant(
                    variants,
                    "size",
                    "small"
                  )
                })
              })
            : null}
        </div>
      ) : null}
      {(
        hasVariant(variants, "icons", "five")
          ? true
          : hasVariant(variants, "icons", "end")
          ? false
          : hasVariant(variants, "icons", "none")
          ? false
          : false
      ) ? (
        <div
          className={classNames(defaultcss.all, sty.freeBox__zpXis, {
            [sty.freeBox__icons_end__zpXison4Z]: hasVariant(
              variants,
              "icons",
              "end"
            ),
            [sty.freeBox__icons_five__zpXiszqPth]: hasVariant(
              variants,
              "icons",
              "five"
            ),
            [sty.freeBox__icons_none__zpXisRfRl]: hasVariant(
              variants,
              "icons",
              "none"
            ),
            [sty.freeBox__size_large__zpXisOz915]: hasVariant(
              variants,
              "size",
              "large"
            ),
            [sty.freeBox__size_small__zpXisYgvP7]: hasVariant(
              variants,
              "size",
              "small"
            )
          })}
        >
          {(
            hasVariant(variants, "icons", "end")
              ? true
              : hasVariant(variants, "icons", "none")
              ? true
              : true
          )
            ? p.renderPlasmicSlot({
                defaultContents: (
                  <IconIcon
                    className={classNames(defaultcss.all, sty.svg__gGdpw)}
                    role={"img"}
                  />
                ),

                value: args.children3222,
                className: classNames(sty.slotChildren3222, {
                  [sty.slotChildren3222__colors_black]: hasVariant(
                    variants,
                    "colors",
                    "black"
                  ),
                  [sty.slotChildren3222__colors_blue]: hasVariant(
                    variants,
                    "colors",
                    "blue"
                  ),
                  [sty.slotChildren3222__colors_gray]: hasVariant(
                    variants,
                    "colors",
                    "gray"
                  ),
                  [sty.slotChildren3222__icons_end]: hasVariant(
                    variants,
                    "icons",
                    "end"
                  ),
                  [sty.slotChildren3222__icons_none]: hasVariant(
                    variants,
                    "icons",
                    "none"
                  ),
                  [sty.slotChildren3222__size_large]: hasVariant(
                    variants,
                    "size",
                    "large"
                  ),
                  [sty.slotChildren3222__size_small]: hasVariant(
                    variants,
                    "size",
                    "small"
                  )
                })
              })
            : null}
        </div>
      ) : null}
      {(
        hasVariant(variants, "icons", "five")
          ? false
          : hasVariant(variants, "icons", "only")
          ? false
          : true
      )
        ? p.renderPlasmicSlot({
            defaultContents: "Enter some text",
            value: args.slot,
            className: classNames(sty.slotSlot, {
              [sty.slotSlot__colors_black]: hasVariant(
                variants,
                "colors",
                "black"
              ),
              [sty.slotSlot__colors_blue]: hasVariant(
                variants,
                "colors",
                "blue"
              ),
              [sty.slotSlot__colors_gray]: hasVariant(
                variants,
                "colors",
                "gray"
              ),
              [sty.slotSlot__icons_both]: hasVariant(variants, "icons", "both"),
              [sty.slotSlot__icons_end]: hasVariant(variants, "icons", "end"),
              [sty.slotSlot__icons_five]: hasVariant(variants, "icons", "five"),
              [sty.slotSlot__icons_only]: hasVariant(variants, "icons", "only"),
              [sty.slotSlot__link]: hasVariant(variants, "link", "link"),
              [sty.slotSlot__size_large]: hasVariant(variants, "size", "large"),
              [sty.slotSlot__size_small]: hasVariant(variants, "size", "small")
            })
          })
        : null}
      {(
        hasVariant(variants, "icons", "both")
          ? true
          : hasVariant(variants, "icons", "end")
          ? true
          : false
      ) ? (
        <div
          className={classNames(defaultcss.all, sty.freeBox__dEqx, {
            [sty.freeBox__icons_both__dEqxJ4Kk9]: hasVariant(
              variants,
              "icons",
              "both"
            ),
            [sty.freeBox__icons_end__dEqxon4Z]: hasVariant(
              variants,
              "icons",
              "end"
            ),
            [sty.freeBox__icons_five__dEqxzqPth]: hasVariant(
              variants,
              "icons",
              "five"
            ),
            [sty.freeBox__size_small__dEqxYgvP7]: hasVariant(
              variants,
              "size",
              "small"
            )
          })}
        >
          {(
            hasVariant(variants, "icons", "both")
              ? true
              : hasVariant(variants, "icons", "end")
              ? true
              : hasVariant(variants, "icons", "none")
              ? false
              : false
          )
            ? p.renderPlasmicSlot({
                defaultContents: (
                  <IconIcon
                    className={classNames(defaultcss.all, sty.svg___8T9Vu)}
                    role={"img"}
                  />
                ),

                value: args.children2,
                className: classNames(sty.slotChildren2, {
                  [sty.slotChildren2__colors_black]: hasVariant(
                    variants,
                    "colors",
                    "black"
                  ),
                  [sty.slotChildren2__icons_both]: hasVariant(
                    variants,
                    "icons",
                    "both"
                  ),
                  [sty.slotChildren2__icons_end]: hasVariant(
                    variants,
                    "icons",
                    "end"
                  ),
                  [sty.slotChildren2__icons_none]: hasVariant(
                    variants,
                    "icons",
                    "none"
                  ),
                  [sty.slotChildren2__link]: hasVariant(
                    variants,
                    "link",
                    "link"
                  )
                })
              })
            : null}
        </div>
      ) : null}
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicButton__VariantsArgs;
    args?: PlasmicButton__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicButton__Fetches;
  } & Omit<PlasmicButton__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicButton__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicButton__ArgProps,
      internalVariantPropNames: PlasmicButton__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicButton__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicButton";
  } else {
    func.displayName = `PlasmicButton.${nodeName}`;
  }
  return func;
}

export const PlasmicButton = Object.assign(
  // Top-level PlasmicButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicButton
    internalVariantProps: PlasmicButton__VariantProps,
    internalArgProps: PlasmicButton__ArgProps
  }
);

export default PlasmicButton;
/* prettier-ignore-end */
